### ISSUE TITLE
default README shouldn't contain `mox init`, it's already init'd!

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/moccasin#171]
![2024-12-02 08 50 52](https://github.com/user-attachments/assets/e48ee05b-2337-45ec-8970-1425bccaa37a)

Perhaps it would be better to have some docs on installing dependencies.

**Comment by Ankush1oo8** [comment]
Shall I fix this?

**Comment by Ankush1oo8** [comment]
Only to remove mox I it right??

**Comment by PatrickAlphaC** [comment]
Ah, sorry @Ankush1oo8, I didn't see your comment! Yes, anything marked `good first issue` you can just fix!
